{
 "title": "Weather DW Overview",
 "tags": [
  "weather",
  "etl",
  "postgres"
 ],
 "time": { "from": "now-72h", "to": "now+72h" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "city_name",
    "label": "City",
    "query": "SELECT DISTINCT city_name FROM mart.mart_city_hourly_risk ORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Alert hours (latest run)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest AS (\n  SELECT run_id\n  FROM meta.etl_runs\n  WHERE status = 'success'\n  ORDER BY finished_at DESC NULLS LAST\n  LIMIT 1\n)\nSELECT count(*) AS alert_hours\nFROM mart.mart_city_hourly_risk m\nJOIN latest l ON m.run_id = l.run_id\nWHERE storm_risk_flag = true\n  AND ('${city_name:csv}' = '$__all' OR city_name IN (${city_name:sqlstring}));"
    }
   ]
  },
  {
   "title": "Top risk by hour",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH latest AS (\n  SELECT run_id\n  FROM meta.etl_runs\n  WHERE status = 'success'\n  ORDER BY finished_at DESC NULLS LAST\n  LIMIT 1\n)\nSELECT city_name, forecast_ts_utc, precipitation, precipitation_probability, weathercode, storm_risk_flag, round(risk_score::numeric,2) AS risk_score\nFROM mart.mart_city_hourly_risk m\nJOIN latest l ON m.run_id = l.run_id\nWHERE ('${city_name:csv}' = '$__all' OR city_name IN (${city_name:sqlstring}))\nORDER BY storm_risk_flag DESC, risk_score DESC, forecast_ts_utc ASC\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Risk score by city",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "WITH latest AS (\n  SELECT run_id\n  FROM meta.etl_runs\n  WHERE status = 'success'\n  ORDER BY finished_at DESC NULLS LAST\n  LIMIT 1\n)\nSELECT forecast_ts_utc AS time, city_name AS metric, risk_score AS value\nFROM mart.mart_city_hourly_risk m\nJOIN latest l ON m.run_id = l.run_id\nWHERE ('${city_name:csv}' = '$__all' OR city_name IN (${city_name:sqlstring}))\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Max risk by city",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "rawSql": "WITH latest AS (\n  SELECT run_id\n  FROM meta.etl_runs\n  WHERE status = 'success'\n  ORDER BY finished_at DESC NULLS LAST\n  LIMIT 1\n)\nSELECT city_name, max(risk_score) AS max_risk\nFROM mart.mart_city_hourly_risk m\nJOIN latest l ON m.run_id = l.run_id\nWHERE ('${city_name:csv}' = '$__all' OR city_name IN (${city_name:sqlstring}))\nGROUP BY city_name\nORDER BY max_risk DESC;"
    }
   ]
  }
 ]
}